### ISSUE TITLE
Ship own ssl lib for supporting TLS1.2 with secure ciphers

### ISSUE THREAD

**Issue by bastelfreak** [sebastianrakel/fb-client-android#2]
The ssl lib on Android 4.4.2 is old and unable to connect to servers with the following cipher settings:
SSLCipherSuite '!EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:!CAMELLIA256:AES256:!CAMELLIA128:AES128:!SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP    :!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA'

they are recommended by the ACH group. firefox is shipping his own ssl lib and able to work  with these ciphers

**Comment by bastelfreak** [comment]
_push_ ?

**Comment by sebastianrakel** [comment]
i will look in to that and try to implement it

**Comment by sebastianrakel** [comment]
i will not fix that, you have to use a newer android version.
