### ISSUE TITLE
crashes when i press upload butten

### ISSUE THREAD

**Issue by treakiandroid** [sebastianrakel/fb-client-android#9]
hi,

i am using android 6 and i guess i have done nothing wrong, but when i press the upload butten the app crashes and is gone. 

please fix that

thanks

**Comment by treakiandroid** [comment]
i have uninstalled the app, i

**Comment by sebastianrakel** [comment]
Some more Infos would be helpful, did it anyone working? Did you have set an apikey?

**Comment by ehwat** [comment]
steps  to reproduce: 1. press upload files

**Comment by sebastianrakel** [comment]
Fixed in 1.2.1
